"use client";

/**
 * Developers — API reference.
 *
 * SRS 3.1: the portal "visualizes the OpenAPI 3.0 documentation".
 *
 * The spec is generated by the running service rather than written by hand, so
 * it cannot describe an endpoint that does not exist or miss one that does.
 * Rendered here as a grouped operation list, with the raw document and the
 * interactive explorer both one click away.
 */

import { useEffect, useState } from "react";
import { Book, External } from "@/components/icons";
import { Badge, Card, Skeleton, cx } from "@/components/ui";
import { API_BASE } from "@/lib/api";

type Operation = { method: string; path: string; summary: string; tag: string };

const METHOD_TONE: Record<string, string> = {
  get: "bg-info-bg text-info",
  post: "bg-violet-100 text-violet-700",
  delete: "bg-danger-bg text-danger",
};

export default function DocsPage() {
  const [operations, setOperations] = useState<Operation[] | null>(null);
  const [version, setVersion] = useState("");

  useEffect(() => {
    void (async () => {
      try {
        const response = await fetch(`${API_BASE}/openapi.json`);
        const spec = (await response.json()) as {
          info: { version: string };
          paths: Record<string, Record<string, { summary?: string; tags?: string[] }>>;
        };
        setVersion(spec.info.version);

        const list: Operation[] = [];
        for (const [path, methods] of Object.entries(spec.paths)) {
          for (const [method, detail] of Object.entries(methods)) {
            list.push({
              method,
              path,
              summary: detail.summary ?? "",
              tag: detail.tags?.[0] ?? "other",
            });
          }
        }
        setOperations(list);
      } catch {
        setOperations([]);
      }
    })();
  }, []);

  const grouped = (operations ?? []).reduce<Record<string, Operation[]>>((acc, op) => {
    (acc[op.tag] ??= []).push(op);
    return acc;
  }, {});

  return (
    <div className="p-6 lg:p-8">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold tracking-tight text-heading">API reference</h1>
          <p className="mt-1 text-[13px] text-muted">
            OpenAPI 3.0{version ? ` · v${version}` : ""} · generated from the running service
          </p>
        </div>
        <div className="flex gap-4 text-[13px] font-semibold">
          <a
            href={`${API_BASE}/docs`}
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-1.5 text-violet-600 hover:text-violet-700"
          >
            <Book className="h-4 w-4" />
            Explorer
          </a>
          <a
            href={`${API_BASE}/openapi.json`}
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-1.5 text-muted hover:text-ink"
          >
            <External className="h-4 w-4" />
            openapi.json
          </a>
        </div>
      </div>

      {operations === null ? (
        <Skeleton className="mt-8 h-40 w-full" />
      ) : (
        <div className="mt-8 space-y-8">
          {Object.entries(grouped).map(([tag, ops]) => (
            <section key={tag}>
              <h2 className="text-[13px] font-semibold uppercase tracking-wide text-subtle">
                {tag}
              </h2>
              <ul className="mt-3 divide-y divide-line">
                {ops.map((op) => (
                  <li key={`${op.method}-${op.path}`} className="flex items-center gap-3 py-2.5">
                    <span
                      className={cx(
                        "w-14 shrink-0 rounded px-1.5 py-0.5 text-center font-mono text-[10px] font-bold uppercase",
                        METHOD_TONE[op.method] ?? "bg-canvas text-muted",
                      )}
                    >
                      {op.method}
                    </span>
                    <code className="shrink-0 font-mono text-[12px] text-ink">{op.path}</code>
                    <span className="min-w-0 flex-1 truncate text-[12px] text-muted">
                      {op.summary}
                    </span>
                  </li>
                ))}
              </ul>
            </section>
          ))}
        </div>
      )}
    </div>
  );
}
